apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata: 
  name: us-east-2a
spec: 
  securityGroups: 
    - sg-0cdbafec57dfdc2aa
    - sg-0fba464519739df9a
  subnet: subnet-052bc89a7d6bffc1b